### ISSUE TITLE
JPA 유튜브 강의 링크가 잘못된 것 같습니다.

### ISSUE THREAD

**Issue by Integerous** [cheese10yun/dev-info#1]
좋은 내용 공유해주셔서 감사합니다.

그런데 JPA 유튜브 강의 링크가 패스트캠퍼스 홈으로 연결됩니다.

좋은 하루 보내세요!

**Comment by cheese10yun** [comment]
@Integerous 
저도 뒤늦게 확인하고 수정 작업했습니다. 이렇게 친절하게 이슈도 올려주신점 진심으로 감사합니다.
