### ISSUE TITLE
오타..?

### ISSUE THREAD

**Issue by BackdevHong** [cheese10yun/dev-info#13]
이건 오타인가요? 아니면 의도하신 건가요?
![오타](https://user-images.githubusercontent.com/97325091/173469661-32460472-29e1-4937-a1b8-fea7a2c3bdcb.png)

**Comment by cheese10yun** [comment]
오타가 맞는데 무슨 말을 하려고 하다가 오타가 나온지 모르겠네요....

**Comment by BackdevHong** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by BackdevHong** [comment]
도서 클린 코드에 대한 풀이 강의라고 적으려다가 근ㄷ를 적으신게 아닐지..
