### ISSUE TITLE
자바8 인 액션 절판입니다!

### ISSUE THREAD

**Issue by hyunssooo** [cheese10yun/dev-info#2]
남은 수량은 판매중이지만 [모던 자바 인 액션](http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9791162242025&orderClick=JAj)이 새로 나왔습니다! :)

**Comment by cheese10yun** [comment]
제보 감사합니다.!
